<a href="https://colab.research.google.com/github/VeerJava2021/nba-game-predictor/blob/main/nba_game_predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install kagglehub
import kagglehub
path = kagglehub.dataset_download("wyattowalsh/basketball")
print(path)

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /usr/local/lib/python3.12/dist-packages (from kagglehub) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (26.2)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2026.6.17)
Downloading to /root/.cache/kagglehub/datasets/wyattowalsh/basketball/238.archive...

100%|██████████| 697M/697M [00:09<00:00, 78.2MB/s]

Extracting files...

/root/.cache/kagglehub/datasets/wyattowalsh/basketball/versions/238

In [4]:
import pandas as pd
games = pd.read_csv(path + "/csv/game.csv")
games.head(20)

,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,fgm_home,...,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away,season_type
0,21946,1610610035,HUS,Toronto Huskies,24600001,1946-11-01 00:00:00,HUS vs. NYK,L,0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,68.0,2,0,Regular Season
1,21946,1610610034,BOM,St. Louis Bombers,24600003,1946-11-02 00:00:00,BOM vs. PIT,W,0,20.0,...,NaN,NaN,NaN,NaN,NaN,25.0,51.0,-5,0,Regular Season
2,21946,1610610032,PRO,Providence Steamrollers,24600002,1946-11-02 00:00:00,PRO vs. BOS,W,0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,-6,0,Regular Season
3,21946,1610610025,CHS,Chicago Stags,24600004,1946-11-02 00:00:00,CHS vs. NYK,W,0,21.0,...,NaN,NaN,NaN,NaN,NaN,22.0,47.0,-16,0,Regular Season
4,21946,1610610028,DEF,Detroit Falcons,24600005,1946-11-02 00:00:00,DEF vs. WAS,L,0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,50.0,17,0,Regular Season
5,21946,1610610026,CLR,Cleveland Rebels,24600006,1946-11-03 00:00:00,CLR vs. HUS,W,0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,60.0,-11,0,Regular Season
6,21946,1610610031,PIT,Pittsburgh Ironmen,24600007,1946-11-04 00:00:00,PIT vs. WAS,L,0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,71.0,15,0,Regular Season
7,21946,1610612738,BOS,Boston Celtics,24600008,1946-11-05 00:00:00,BOS vs. CHS,L,0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,57.0,2,0,Regular Season
8,21946,1610610028,DEF,Detroit Falcons,24600009,1946-11-05 00:00:00,DEF vs. BOM,L,0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,4,0,Regular Season
9,21946,1610610032,PRO,Providence Steamrollers,24600011,1946-11-07 00:00:00,PRO vs. CHS,W,0,31.0,...,NaN,NaN,NaN,NaN,NaN,14.0,65.0,-8,0,Regular Season
10,21946,1610610034,BOM,St. Louis Bombers,24600012,1946-11-07 00:00:00,BOM vs. NYK,L,0,25.0,...,NaN,NaN,NaN,NaN,NaN,16.0,68.0,5,0,Regular Season
11,21946,1610612744,PHW,Philadelphia Warriors,24600010,1946-11-07 00:00:00,PHW vs. PIT,W,0,28.0,...,NaN,NaN,NaN,NaN,NaN,35.0,75.0,-6,0,Regular Season
12,21946,1610610035,HUS,Toronto Huskies,24600013,1946-11-08 00:00:00,HUS vs. DEF,W,0,31.0,...,NaN,NaN,NaN,NaN,NaN,15.0,71.0,-2,0,Regular Season
13,21946,1610610034,BOM,St. Louis Bombers,24600014,1946-11-09 00:00:00,BOM vs. WAS,W,0,28.0,...,NaN,NaN,NaN,NaN,NaN,26.0,69.0,-1,0,Regular Season
14,21946,1610610032,PRO,Providence Steamrollers,24600015,1946-11-09 00:00:00,PRO vs. PIT,W,0,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,66.0,-10,0,Regular Season
15,21946,1610610025,CHS,Chicago Stags,24600016,1946-11-09 00:00:00,CHS vs. HUS,W,0,22.0,...,NaN,NaN,NaN,NaN,NaN,23.0,54.0,-10,0,Regular Season
16,21946,1610610028,DEF,Detroit Falcons,24600017,1946-11-09 00:00:00,DEF vs. BOS,W,0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,46.0,-23,0,Regular Season
17,21946,1610610026,CLR,Cleveland Rebels,24600018,1946-11-10 00:00:00,CLR vs. WAS,W,0,42.0,...,NaN,NaN,NaN,NaN,NaN,NaN,68.0,-24,0,Regular Season
18,21946,1610612752,NYK,New York Knicks,24600020,1946-11-11 00:00:00,NYK vs. CHS,L,0,26.0,...,NaN,NaN,NaN,NaN,NaN,21.0,78.0,10,0,Regular Season
19,21946,1610610031,PIT,Pittsburgh Ironmen,24600019,1946-11-11 00:00:00,PIT vs. PRO,W,0,29.0,...,NaN,NaN,NaN,NaN,NaN,28.0,71.0,-13,0,Regular Season

In [5]:
games['season_id'] = games['season_id'].astype(str)
games['season'] = games['season_id'].str[1:].astype(int)  # strips the leading '2'

recent_games = games[games['season'] >= 2015].copy()
print(recent_games.shape)
recent_games.head()

(10674, 56)

,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,fgm_home,...,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away,season_type,season
55024,22015,1610612737,ATL,Atlanta Hawks,21500001,2015-10-27 00:00:00,ATL vs. DET,L,240,37.0,...,23.0,5.0,3.0,15.0,15.0,106.0,12,1,Regular Season,2015
55025,22015,1610612744,GSW,Golden State Warriors,21500003,2015-10-27 00:00:00,GSW vs. NOP,W,240,41.0,...,21.0,9.0,3.0,19.0,26.0,95.0,-16,1,Regular Season,2015
55026,22015,1610612741,CHI,Chicago Bulls,21500002,2015-10-27 00:00:00,CHI vs. CLE,W,240,37.0,...,26.0,5.0,7.0,11.0,21.0,95.0,-2,1,Regular Season,2015
55027,22015,1610612738,BOS,Boston Celtics,21500005,2015-10-28 00:00:00,BOS vs. PHI,W,240,39.0,...,12.0,11.0,6.0,24.0,22.0,95.0,-17,1,Regular Season,2015
55028,22015,1610612748,MIA,Miami Heat,21500008,2015-10-28 00:00:00,MIA vs. CHA,W,240,36.0,...,16.0,4.0,1.0,9.0,16.0,94.0,-10,1,Regular Season,2015